apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrc
  labels:
     app: javaapp
spec:
 replicas: 2
 selector:
   matchLabels:
     type: webserver
 template:
   metadata:
     name: testpod
     labels:
       type: webserver
       env: QA
   spec:
    containers:
     - image: mynginx
        name: myc1
